export const biography = [
  '<p>My name is Ali Memarzadeh, 29 years old and I live in Tehran, Iran. Please click on Continue if you wish to read my short biography. </p>',
  "<p>Let me start from age 18, when I got a decent rank in Iran's national exam of university entrance. In Iran this exam happens in early stages of youth and therefore many attendants do not yet know exactly what field they are born for, choosing a field they will either drop or change some years later. Being not an exception, I made the same mistake. I studied civil engineering at one of the best-known universities of Iran (<a href=https://en.sharif.edu/ target='_blank'>Sharif</a>), but I didn't enjoy its core subjects and only took pleasure when it came to computer and programming. Even I planned my M.Sc. thesis so that it contained much of programming. </p>",
  "<p>After M.Sc. graduation, I was 24 and it was time to go to military service for two years. But fortunately, I managed to contract a governmental project to receive a military service reduction, although this task also took two years, meanwhile I had enough time to have secondary jobs related to my field of study. This period helped me to make sure I was not born to become a civil engineer and I don't want to waste my life on it. </p>",
  "<p>Finishing military service and almost totally letting go of my academic background, I got familiar with Forex market and liked it. Guess why? It demanded much programming to develop trading robots in <a href=http://www.mql5.com target='_blank'>MQL5</a> language (a language based on C++). </p>",
  '<p>I spent around one year on Forex and developing trading robots, also did some freelance on it for others. At last, I came to realize that the only thing I have been doing in all these years and have loved it, has been programming. Besides, although reaching a relatively profitable strategy and developing its robot, again I felt somewhere in bottom of my heart that this job does not conform to my personal <a href=#motto>motto</a>. </p>',
  "<p>Finally, I made the right decision and moved to development seriously and diligently. Only having my cousin as a mentor who showed me the way, I started to learn web development fast. From HTML to CSS to JavaScript to React to its famous libraries and etc. Meanwhile I took a course at <a href=http://www.mftplus.com target='_blank' >MFT</a> to learn Android programming out of enjoy and curiosity. </p>",
  '<p>Long story made short, now I am standing at a point claiming <span style=font-weight:700>"I know web development and I can learn anything new in less than two week.” </span> </p>',
];
