export const biography = [
  'Hello. I am Ali Memarzadeh, 29 years old and live in Tehran, Iran. I developed this site with the single aim of presenting my skills in web development. Click on Continue if you wish to read a short summary of what paths I took in my life up until now. ',
  "Let me start from age 18, when I got a decent rank in Iran national university entrance exam. In Iran this exam happens in early stages of youth and therefore many attendants do not yet know what field they are made for exactly, choosing field they will either drop or change some years later. Being not an exception, I made the same mistake. I studied civil engineering at best-known university of Iran (Sharif), but I didn't enjoy its core subject and only took pleasure when it came to computer and programming. Even I planned my M.Sc thesis so that it contains much programming. ",
  "After  M.Sc graduation, I was 24 and it was time to go to military service for 2 years. But fortunately I managed to contract a governmental project to recieve a military service reduction, although this task also took two years, I had enough time to have secondary jobs related to my field of study. This period helped me to make sure I am no made for civil engineering and I don't want to waste my life on it. ",
  'Finishing military service and almost totally letting go of my academic background, I got familiar with Forex market and liked it. Guess why? It needed much programming to develop trading robots in MQL5 language.',
  'I spent around one year on Forex and developing trading robots, also did some freelance on it for others. At last I came to realize that the one thing I have been doing in all these years and have loved it, was programming. Besides, although reaching a reletively profitable strategy and developing its robot, I felt somewhere in bottom of my heart that this job does not conform to my personal <span>motto</span>.',
  'Finally I made the right decision and moved to development seriously and deligently. Only having my cousin as a mentor who showed me the way, I started to learn web development fast. From HTML to CSS to Javascript to React to its famous libraries and etc. Meanwhile I took a course at <span>MFT</span> to learn Android programming out of curiousity.',
  'Now...I am standing at a point claiming <span>"I Know Web Development and I Can Learn Anything In Less Than Two Week."</span>',
];
